### ISSUE TITLE
Reporte. Proyecto final. Software Gestor de libros.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/proyecto-final-check_team#2]
[Gestor de libros F.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-check_team/files/6779989/Gestor.de.libros.F.pdf)

**Comment by Edwin38H** [comment]
calificacion 80
buen trabajo compañeros

**Comment by josealfredo79** [comment]
Bien hecho y revisado
